version: "2.1"

services:
   postgres:
    image: postgres:9.5.2
    environment:
      POSTGRES_DB      : ontrack
      POSTGRES_USER    : ontrack
      POSTGRES_PASSWORD: ontrack
   influxdb:
    image: influxdb:1.5.2
   ontrack:
      image: "docker.nemerosa.net/nemerosa/ontrack:${ONTRACK_VERSION:-latest}"
      depends_on:
         postgres:
            condition: service_started
         influxdb:
           condition: service_started
      environment:
         PROFILE: acceptance
         ONTRACK_CONFIG_CONFIGURATION_TEST: "false"
         JAVA_OPTIONS: "-Xmx2048m -Xms2048m"
         SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres/ontrack"
         # InfluxDB being enabled
         ONTRACK_INFLUXDB_ENABLED: "true"
         ONTRACK_INFLUXDB_URI: "http://influxdb:8086"
   ontrack_kdsl:
      image: "docker.nemerosa.net/nemerosa/ontrack-kdsl-test:${ONTRACK_VERSION:-latest}"
      depends_on:
         ontrack:
            condition: service_healthy
      environment:
         JAVA_OPTIONS: "-Xmx2048m -Xms2048m"
         BDD_MODEL_ONTRACK_URI: "http://ontrack:8080"
         BDD_MODEL_ONTRACK_USERNAME: "admin"
         BDD_MODEL_ONTRACK_PASSWORD: "admin"
      volumes:
         - "./build:/ontrack/test/output:rw"
